### ISSUE TITLE
[Question] How to use Model.filtered or Model.filtered_domain?

### ISSUE THREAD

**Issue by albertosottile** [OCA/odoorpc#99]
I am using OdooRPC 0.10.1 on Odoo 14.0 SaaS (`protocol='jsonrpc+ssl'`) and Python 3.11. 
No matter what I try, I do not seem to be able to use `filtered` or `filtered_domain`.

These are the two errors that I get (assume `RepairOrder = odoo.env['repair.order']`)

```
>>> RepairOrder.filtered(lambda r: True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.11/site-packages/odoorpc/models.py", line 59, in rpc_method
    result = cls._odoo.execute_kw(cls._name, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/odoorpc/odoo.py", line 524, in execute_kw
    data = self.json(
           ^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/odoorpc/odoo.py", line 271, in json
    data = self._connector.proxy_json(url, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/odoorpc/rpc/jsonrpclib.py", line 110, in __call__
    data_json = json.dumps(data)
                ^^^^^^^^^^^^^^^^
  File "/Users/albertos/.asdf/installs/python/3.11.9/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertos/.asdf/installs/python/3.11.9/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/albertos/.asdf/installs/python/3.11.9/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/Users/albertos/.asdf/installs/python/3.11.9/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type function is not JSON serializable
```

and

```
>>> RepairOrder.filtered_domain([('lot_id.name', 'ilike', 'NAME')])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.11/site-packages/odoorpc/models.py", line 59, in rpc_method
    result = cls._odoo.execute_kw(cls._name, method, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.11/site-packages/odoorpc/odoo.py", line 524, in execute_kw
    data = self.json(
           ^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/odoorpc/odoo.py", line 273, in json
    raise error.RPCError(
odoorpc.error.RPCError: filtered_domain() missing 1 required positional argument: 'domain'
```

Am I doing something wrong? Both these methods should be available in Odoo 14. 

Thanks for your assistance.

(sorry for the initial state of this issue, I pressed Enter after the title and GitHub created an empty issue...)

**Comment by x2nie** [comment]
I felt you faced 2 different mistake.
1. for the filtered, I think you can't call that method remotely (using odoorpc), because this library can only send/receive a valid json; and `lambda` is not a valid json. valid json are: dict, list, string, int, float, boolean. However, You might want to call the `search` first, and do something with the search result to get a similar result with `filtered`.
2. I am not sure that your domain is valid. (that is field name with a dot = valid for odoo 17, but dunno for prior odoo).  However, try to wrap your domain within a list, perhaps that works. OR, change the tuple brackets `( )` with list bracket `[ ]`

**Comment by albertosottile** [comment]
Thanks for the reply. Actually, I realized I was doing an even more fundamental mistake. The methods `filtered` and  `filtered_domain` are part of the [ORM API](https://www.odoo.com/documentation/14.0/developer/reference/addons/orm.html#) but not of the [External API](https://www.odoo.com/documentation/14.0/developer/reference/external_api.html). Therefore, there should not be a way to call these from `odoorpc`. 

I would definitely have appreciated a clearer error message. However, this does not change the fact that these methods are unusable. Therefore, I think we can close this issue.

**Comment by x2nie** [comment]
That is not true. You can call almost any method within any model. (but however in your case, you can mark this issue as closed as well).

The problem in your case is not about External API,
the problem is that one parameter expected by `filtered` method is a python function / `lambda`, but OdooRpc can't deliver python function (lambda) because OdooRPC can only send any valid JSON. and lambda (function) is not a valid json.
